vtex-apps/reviews-and-ratings

CHANGELOG.md, manifest.json
Bumped version number and updated changelog
=> Release v1.1.2

CHANGELOG.md, docs/README.md, dotnet/GraphQL/Types/AppSettingsType.cs, dotnet/Models/AppSettings.cs, graphql/appSettings.graphql, graphql/schema.graphql, manifest.json, react/ReviewForm.tsx, react/Reviews.tsx, react/package-lock.json, react/package.json, react/yarn.lock
setting added to open review accordions by default with show more/show less link
=> wrike 475520282 - add setting to reviews to default reviews to open

.all-contributorsrc, .github/CODEOWNERS, docs/README.md
This an automated pull request that aims to:
- Update CODEOWNERS content
- Update .all-contributorsrc file
=> Update codeowners and add all-contributors

CHANGELOG.md, docs/README.md, react/Reviews.tsx
**What problem is this solving?**
Adds two new CSS handles. Solves https://github.com/vtex-apps/reviews-and-ratings/issues/19
**How should this be manually tested?**
[Workspace](https://iaronaraujo--storecomponents.myvtex.com/fashion-eyeglasses/p)
**Screenshots or example usage:**
=> Add 2 new CSS handles.

CHANGELOG.md, docs/README.md, react/RatingSummary.tsx, react/Reviews.tsx
**What problem is this solving?**
Previous release added ld+json structured data for reviews, but use of single quotes made it invalid JSON. New commit implements JSON.stringify to ensure JSON is valid.
**How should this be manually tested?**
Linked here: https://reviewseo--redoxx.myvtex.com/booty-boss-70002/p
=> Change single quotes to double quotes in ld+json

CHANGELOG.md, react/ReviewForm.tsx
Fix error on console:
Fixed workspace:
https://reviewinput--storecomponents.myvtex.com/classic-shoes/p
n/a
=> Fix value prop on input of email

CHANGELOG.md, docs/README.md, react/Reviews.tsx
=> Css handlers

CHANGELOG.md, dotnet/service.json
Adjusting `replica` settings for the infrastructure to define dynamic scale range
=> Setting infrastructure REPLICA parameters

CHANGELOG.md, dotnet/service.json
Setting infrastructure replica parameters
=> Setting infrastructure  parameters

CHANGELOG.md, docs/README.md, dotnet/GraphQL/Types/AppSettingsType.cs, dotnet/Models/AppSettings.cs, graphql/appSettings.graphql, graphql/schema.graphql, manifest.json, messages/context.json, messages/en.json, messages/es.json, messages/pt.json, react/RatingSummary.tsx, react/Reviews.tsx, react/ReviewsGraph.tsx, react/styles.css
I added new features on product-rating-summary. They are all active on the workspace:
1. Ability to display stars even if the product has no reviews
2. Ability to hide the total number of reviews in product-rating-summary block
3. Ability to add `Add Review` button under the stars in product-rating-summary block
[Workspace](https://longo--customsoft.myvtex.com/ceas-crystal-frost-ls-hthtsts-5484070/p)
=> New features on product-rating-summary

CHANGELOG.md, dotnet/Controllers/RoutesController.cs, dotnet/DataSources/AppSettingsRepository.cs, dotnet/DataSources/ProductReviewRepository.cs, dotnet/Models/RatingResponse.cs, dotnet/ReviewsRatings.csproj, dotnet/Services/ProductReviewService.cs, dotnet/StartupExtender.cs, manifest.json
Logging to aid in problem resolution
Add/remove reviews, retrieve reviews
POST https://rar--sandboxusdev.myvtex.com/reviews-and-ratings/api/review
{
"ProductId": "13",
"Rating": 5,
"Title": "Great Product",
"Text": "Great mouse at reasonable price"
}
https://rar--sandboxusdev.myvtex.com/reviews-and-ratings/api/rating/13
https://rar--sandboxusdev.myvtex.com/reviews-and-ratings/api/reviews?order_by=ReviewDateTime
https://media.giphy.com/media/jU3Oz64GHix56dhZ1V/giphy.gif
=> Added logging

CHANGELOG.md, manifest.json
Needed to add outbound access policies
https://rar--sandboxusdev.myvtex.com/reviews-and-ratings/api/review
=> Added outbound access policies

CHANGELOG.md, dotnet/DataSources/ProductReviewRepository.cs
=> Changed user validation url

CHANGELOG.md, dotnet/service.json
Setting CPU factor by `25`
Closes #63
=> Changing CPU factor from 250 to 25

CHANGELOG.md, react/RatingSummary.tsx, react/Reviews.tsx
This is modifying the structured data so that Google is able to properly interpret the reviews and ratings block on the product page. 
The workspace/product I used: https://tonysheng--sandboxusdev.myvtex.com/navel-oranges-grown-large-fresh-fruit/p
And the Google rich text results: https://search.google.com/test/rich-results?id=tIPhofSbzGncHXLBm2Gx6Q
=> Add @id property to structured data

CHANGELOG.md, dotnet/Services/ProductReviewService.cs
Anonymous reviews are not saving
https://brian--sandboxusdev.myvtex.com/
=> Fix for anonymous review submission

CHANGELOG.md, docs/README.md, react/RatingSummary.tsx, react/ReviewForm.tsx, react/Reviews.tsx
It gives you the possibility to better style the components.
Link the app.
[Workspace](https://prreviews--iviteb.myvtex.com/papusa-3/p)
Tryed styling it using current classes.
=> added multiple css handles

CHANGELOG.md, dotnet/Controllers/RoutesController.cs, dotnet/GraphQL/Mutation.cs, dotnet/Services/IProductReviewService.cs, dotnet/Services/ProductReviewService.cs
Fix validation of reviews submitted through the API
curl --location --request POST 'https://brian--sandboxusdev.myvtex.com/reviews-and-ratings/api/review' \
--header 'VtexIdclientAutCookie: ' \
--header 'Content-Type: application/json' \
--data-raw '{
"productId": "277",
"rating": 5,
"title": "Buen Producto",
"text": "100% recomendada..."
}'
[Workspace](Link goes here!)
https://brian--sandboxusdev.myvtex.com/reviews-and-ratings/api/review
=> Fix to API user validation

CHANGELOG.md, dotnet/DataSources/ProductReviewRepository.cs, manifest.json
- `Get_Account_By_Identifier` policy
- Removed sensitive information from log
- 
[Workspace](https://reviews--sandboxusdev.myvtex.com/_v/private/vtex.reviews-and-ratings@2.11.3/graphiql/v1?query=%7B%0A%20%20reviews%20%7B%0A%20%20%20%20data%20%7B%0A%20%20%20%20%20%20title%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A)
=> Adding required policy and removing sensitive information from log

CHANGELOG.md, docs/README.md, react/Reviews.tsx
This PR adds a CSS handle for the review pagination container.
=> Add a CSS handle for review pagination container

CHANGELOG.md, dotnet/GraphQL/Query.cs, dotnet/GraphQL/Types/ReviewInputType.cs, dotnet/GraphQL/Types/ReviewType.cs, dotnet/Models/Review.cs, dotnet/Services/ProductReviewService.cs, graphql/schema.graphql
https://vtex-dev.atlassian.net/browse/REVIEWS-11
=> Fix to editing review

CHANGELOG.md, dotnet/Services/ProductReviewService.cs
Imported reviews not showing on Pending tab
Import new review via API, check Pending tab in Review admin
https://brian--sandboxusdev.myvtex.com/admin/reviews-ratings/pending/
=> Default to false when Approved is null

CHANGELOG.md, dotnet/Controllers/RoutesController.cs, dotnet/DataSources/AppSettingsRepository.cs, dotnet/DataSources/ProductReviewRepository.cs, dotnet/GraphQL/Query.cs, dotnet/Services/ProductReviewService.cs, dotnet/service.json
=> Limit number of records

CHANGELOG.md, dotnet/Controllers/RoutesController.cs, dotnet/Services/ProductReviewService.cs
=> Data migration error handing

CHANGELOG.md, dotnet/DataSources/ProductReviewRepository.cs
Clone of #106 on branch `2.x`.
=> [2.x] Use metric instead of logs to reduce log volume

CHANGELOG.md, dotnet/Controllers/RoutesController.cs, graphql/schema.graphql
=> [2.x] Add cache to GraphQL queries

CHANGELOG.md, dotnet/Controllers/RoutesController.cs, dotnet/DataSources/AppSettingsRepository.cs, dotnet/DataSources/IProductReviewRepository.cs, dotnet/DataSources/ProductReviewRepository.cs, dotnet/GraphQL/Mutation.cs, dotnet/GraphQL/Query.cs, dotnet/Models/ReviewsResponseWrapper.cs, dotnet/Services/IProductReviewService.cs, dotnet/Services/ProductReviewService.cs, graphql/schema.graphql
Pagination
Performance improvements
Add review, approve
https://brian--sandboxusdev.myvtex.com/
https://brian--sandboxusdev.myvtex.com/admin/reviews-ratings/pending/
=> Performance improvements

CHANGELOG.md, manifest.json
Fixed settings admin messages on the manifest file.
=> [REVIEWS-32] Fixed settings admin messages on the manifest file

CHANGELOG.md, dotnet/Controllers/RoutesController.cs
[Slack conversation about the problem](https://vtex.slack.com/archives/CFJU5HYTV/p1639691206085500?thread_ts=1639673092.074300&cid=CFJU5HYTV)
=> REVIEWS: Specify how long the response should be cache

CHANGELOG.md, dotnet/Controllers/RoutesController.cs, yarn.lock
Bugfix for the rating field parsing issues in file `dotnet/Controllers/RoutesController.cs`, the int.parse throw exceptions for null value and empty strings. Now using int.TryParse which parse value 0 for null and empty strings.
In postman, try [http://aurora--sandboxusdev.myvtex.com/api/dataentities/productReviews/search?_fields=_all&_schema=reviewsSchema&productId=880003&rating=](url) with a null or empty value for the rating, or without the rating field
=> [REVIEWS-39] Fixed rating parse

.github/workflows/lint.yml, .github/workflows/pull-request.yml, .github/workflows/sonarcloud-dotnet.yml, .github/workflows/sonarcloud-ts.yml, CHANGELOG.md, sonar-project.properties
Just adding Quality Engineering actions.
=> ADD Quality Engineering Actions

CHANGELOG.md, docs/README.md
v2 to v3
Improve documentation for the upgrade from v2 to v3
=> [REVIEWS-27] Improve documentation for the upgrade from

CHANGELOG.md, dotnet/Services/ProductReviewService.cs
Bugfix for `totalReviewsByProductId ` query, update a search query for it.
Test if you see the product average stars
[https://arturo--columbiacl.myvtex.com/_v/segment/admin-login/v1/login?returnUrl=%2Fclb-pantalon-hombre-silver-ridge-ii-st-p-1839331%2Fp%3F](url)
=> [REVIEWS]bugfix for average ratings

CHANGELOG.md, dotnet/Services/ProductReviewService.cs
`GetReviewsByProductId` url request fixed.
[Workspace to test](https://tikcet2--columbiacl.myvtex.com/clb-zapatilla-hombre-redmond-v2-wp-1865091/p?property__Color=(255)%20MUD)
=> [REVIEWS] GetReviewsByProductId url request fixed.

CHANGELOG.md, dotnet/DataSources/ProductReviewRepository.cs
Fix the ValidateKeyAndToken function alerts, added retry and maximum retry is 5 times
=> [REVIEWS-70] fix validation alerts

CHANGELOG.md, react/admin/components/util/ApplyMatchButton.tsx
Approving a comment loads in an infinite loop
[Workspace to test](https://arturoreviews--sandboxusdev.myvtex.com/admin/)
=> [REVIEWS-72] Set  to false awaitRefetchQueries

CHANGELOG.md, dotnet/DataSources/ProductReviewRepository.cs
- Change the order of the PUT calls, i put first the verify schema and then the hashed one in vBase.
- Throw Exception message if the first put schema status code `!IsSuccessStatusCode` or `NotModified`
[Slack conversation reference](https://vtex.slack.com/archives/G0130K32X6G/p1645644137685289?thread_ts=1645643981.987329&cid=G0130K32X6G)
=> [REVIEWS-73] Return Try Again message in verify Schema function.

CHANGELOG.md, dotnet/GraphQL/Mutation.cs, dotnet/GraphQL/Query.cs, dotnet/GraphQL/Types/EditReviewInputType.cs, graphql/editReview.graphql, graphql/schema.graphql
Create the `EditReviewInputType` for the editReview mutation.
Set default values to from and to variables in the graphQL schema.
[Workspace to test](https://arturoreviews--sandboxusdev.myvtex.com/admin/graphql-ide)
=> [REVIEWS-78] Add EditReviewInputType for mutation editReview

cypress/integration/2.1.2-signed_in_user.spec.js, cypress/integration/2.2.3-signed_in_user.spec.js, cypress/integration/2.6-graphql.spec.js, cypress/support/graphql_queries.js
a) When admin approval is disabled -> Review should get auto approved( So, removed approved testcase )
b) Added reviewByDateRange testcase
c) Removed reviewByDateTime testcase
=> Added reviewByDateRange testcase

CHANGELOG.md, react/RatingSummary.tsx, react/ReviewForm.tsx, react/admin/index.tsx, react/package.json, react/utils/eventBus.ts, react/yarn.lock, yarn.lock
The rating summary component was not updating when a new review was saved in the front.
I create a new file inside the utils folder to export the eventBus object that contains three functions, i'm using the dispatch function to create a custom event, and the rest of the function could help for future implementations related with event listeners.
Go the workspace to test and create a new review, you should see the new review added in the front as well as the rating-summary block:
[Workspace to test](https://arturoreviews--sandboxusdev.myvtex.com/invicta-pro-diver-swiss-movement-quartz-watch---stainless-steel-case---model-0003/p)
=> [REVIEWS-91] Create a custom eevnt to update RatingsSummary component

cy-runner.yml, cypress/integration/2.5-rest_apis.spec.js, cypress/support/review_and_ratings.apis.js, cypress/support/review_and_ratings.outputvalidation.js
1. Create Review/ Reviews - REST API payload been changed (Updated in cypress tests)
2. Simplified cy-runner.yml
=> Fixed REST API and added few more testcases + updated cy-runner.yml

CHANGELOG.md, dotnet/DataSources/ProductReviewRepository.cs
High level of errors from VerifySchema function
Change existing schema
Visit admin page
Verify that the schema has been updated
```
curl --location --request PUT 'http://sandboxusdev.vtexcommercestable.com.br/api/dataentities/productReviews/schemas/reviewsSchema' \
```
[[Workspace](Link goes here!)](https://brian--sandboxusdev.myvtex.com/admin/reviews-ratings)
=> Updated VerifySchema function

CHANGELOG.md, messages/ar-SA.json, messages/bg-BG.json, messages/context.json, messages/en.json, messages/es.json, messages/fr-FR.json, messages/it-IT.json, messages/ja-JP.json, messages/ko-KR.json, messages/nl-NL.json, messages/pt.json, messages/ro-RO.json, messages/th-TH.json, package.json, react/admin/index.tsx, react/package.json, react/yarn.lock
As simple as translating the Migrate Data button.
=> [REVIEWS-106] Translate migrate data button.

CHANGELOG.md, dotnet/Controllers/RoutesController.cs, dotnet/DataSources/ProductReviewRepository.cs, dotnet/Services/ProductReviewService.cs
To reduce log noise:
Reduced calls to Verify Schema to instances when we should have valid credentials
Changed Task Cancelled errors to warnings.
=> REVIEWS-108

CHANGELOG.md, admin/navigation.json, dotnet/DataSources/AppSettingsRepository.cs, dotnet/DataSources/ProductReviewRepository.cs, dotnet/Services/ProductReviewService.cs
[Workspace to test](https://arturoreviews--sandboxusdev.myvtex.com/)
=> [REVIEWS-111] App review

CHANGELOG.md, dotnet/service.json
Increase the memory for service.json file
=> Increase memory in services json

cypress/integration/2.1.1-anonymous_user.spec.js, cypress/support/commands.js, cypress/support/graphql_testcase.js, cypress/support/selectors.js
- Verify updating the default rating value 0 is not allowed
- Verifying default stars are not zero in storefront while adding ratings to the product.
=> Ratings validation

CHANGELOG.md, cypress/support/commands.js
What problem is this solving?
- Added assertions before targeting a selectors
#changingTooling
=> ENGINEERS-996 product search fixes

CHANGELOG.md, messages/pt.json
Fix typo in Portuguese translation. Tracked in task [LOC-9727](https://vtex-dev.atlassian.net/browse/LOC-9727).
=> Fix typo in Portuguese translation.

CHANGELOG.md, cypress/support/testcase.js
Added UpdateRetry method to verify average rating and messages 
#changingTooling
=> Selector visibility fix

CHANGELOG.md, cy-runner.yml, cypress/integration/2.5-rest_apis.spec.js, cypress/support/api_testcase.js
Adding Hard retries
#changingTooling
=> Adding Hard retries while verifying average ratings

CHANGELOG.md, messages/ar-SA.json, messages/bg-BG.json, messages/context.json, messages/de-DE.json, messages/en.json, messages/es.json, messages/fr-FR.json, messages/id-ID.json, messages/it-IT.json, messages/ja-JP.json, messages/ko-KR.json, messages/nl-NL.json, messages/pt.json, messages/ro-RO.json, messages/th-TH.json, react/Reviews.tsx
There are some "buttons" that show texts in English instead of the region itself.
[Workspace](https://aa254--lojausereserva.myvtex.com/camiseta-estampada-r-pica-pau-class0071847/p)
=> Translating ShowMore component to portuguese

CHANGELOG.md, dotnet/Services/ProductReviewService.cs
=> Use wildcard as fallback

CHANGELOG.md, dotnet/Services/ProductReviewService.cs
Add missing parenthesis and ampersand
=> Add missing parenthesis and ampersand

CHANGELOG.md, dotnet/Services/ProductReviewService.cs
Otherwise we were only capturing the "OR"
=> Fix substring startIndex
