- CHANGELOG.md
- admin/navigation.json
- docs/README.md
This PR setups the "Reviews" app into the new admin v4.
Due to the new admin v4 release, the information architecture of the admin sidebar has completely changed. New sections were created, some old sections were deleted and many apps were moved among these sections. So, the admin-shell team had to make a bunch of refactors on builder-hub and admin-graphql. With those finished, we can now integrate all the apps into the new setup and also keep them working normally on admin v3.
1. Navigate on the sidebar and look for "Reviews" under "Products" section
[Workspace](https://newadmin--storecomponents.myvtex.com/admin)
> Add Admin V4 navigation setup.

- CHANGELOG.md
- admin/navigation.json
Reviews and Ratings app is not positioned in the sidebar where it should be.
Enter this [workspace](https://appsposition--recorrenciaqa.myvtex.com/admin) and open the sidebar second level in the Products section and you'll notice Reviews is second-to-last.
https://github.com/vtex/admin-graphql/pull/174
> Add prop position to navigation item object

- CHANGELOG.md
- dotnet/service.json
This app has a high CPU consumption even when no request is being processed.
Not sure if it is something related to .NET or some background job it is performing.
Currently, each pod receives 80 mCPU and scales when consumes 95% of that.
But the background processing is more than enough to make it scale until it hits 
the max replicas cap.
This makes us consume 80 * 256 MB of memory in each cluster.
Chaging CPU request to 250 mCPU leaves us with 2 replicias each consuming 180~200m CPU.
I kindly ask that someone who develops the app helps me test it.
It shouldn't change functionality, but we need to ensure we're not breaking anything.
> Add CPU spec

- CHANGELOG.md
- dotnet/Controllers/RoutesController.cs
- dotnet/DataSources/ProductReviewRepository.cs
- dotnet/Models/ValidateKeyAndToken.cs
- dotnet/Models/ValidatedKeyAndToken.cs
- manifest.json
Slack thread: https://vtex.slack.com/archives/C90SGTR6U/p1627047419288900
In a nutshell, this PR uses a new authentication strategy when a user calls this app's API endpoints using a VTEX app key and app token pair as the request credentials:
First, the app key and app token are validated by VTEX ID.
Then, the app key is validated by License Manager to check if it has been granted access to at least one resource.
New version linked here: https://quotes--sandboxusdev.myvtex.com/
> Fix app key / app token validation

- CHANGELOG.md
- react/ReviewForm.tsx
Previously, users could click the "Submit Review" button multiple times while the action was being executed, resulting in multiple review submissions. This PR adds a loading state to the button, so that it cannot be clicked again while the original action is still being executed.
Linked here: https://quotes--sandboxusdev.myvtex.com/cauliflower-fresh/p
(Ignore the duplicated review components, that's a store-theme issue)
> Add loading state to Submit Review button to prevent duplicate reviews

- CHANGELOG.md
- dotnet/Services/ProductReviewService.cs
bug fix for review filters
CASE1: PastReviews && locale --- use `_where=` to filter locale value OR locale is null
CASE2: 1. PastReviews && (!locale)    --- showing all reviews, so does not filter by locale
2 (!PastReviews) && locale    --- normally filter locale, does not need `_where=` 
3 (!PastReviews) && (!locale)--- not possible
go to any product page, and see if the average stars shows
> [REVIEWS] bugfix

- CHANGELOG.md
- react/RatingSummary.tsx
Google Search Console is penalizing PDPs SEO with values = 0 for reviewValue and reviewCount [vtex.reviews-and-ratings@2.12.6 pcbox]
SOLUTION: We decided that the ld+json structured data should only be rendered if there are actually reviews (i.e. if the total rating is > 0).
> [REVIEWS-62] Structured data rendered only if reviews > 0.

- CHANGELOG.md
- react/Reviews.tsx
- react/admin/components/DownloadTable.tsx
- react/admin/components/ReviewsTable.tsx
The reviews sorted by date was wrong because ir was using `reviewsDateTime`, but this value is not a timestamp string date, now the app uses `searchDate` that it does.
[Workspace to test](https://arturovtexapps--minisomx.myvtex.com/admin/reviews-ratings/pending/?elements=15&from=15&sortOrder=DESC&sortedBy=date&to=30)
> [REVIEWS-74] Use search-date field for sort

- .github/workflows/cypress.yml
1. Avoid wast time running tests when the PR is triggered byt GitHub Dependabot
2. Installation of Chrome removed, as the new Ubuntu image has it already
> FIX Avoid run Cypress by Dependabot

- CHANGELOG.md
- react/RatingSummary.tsx
The component was waiting until product Id in PDP is available to first render, now the app render the loading message before product Id is available.
[Workspace to test](https://arturoreviews--sandboxusdev.myvtex.com/invicta-pro-diver-swiss-movement-quartz-watch---stainless-steel-case---model-0003/p)
> [REVIEWS-79] Render loading message before product page completely loads

- .github/workflows/cypress.yml
Just fixing schedule tab on GitHub Actions for Cypress.
> FIX GitHub Action schedule typo

- CHANGELOG.md
- dotnet/DataSources/ProductReviewRepository.cs
- dotnet/GraphQL/Query.cs
- graphql/reviewByreviewDateTime.graphql
- graphql/schema.graphql
When using the `reviewByDateRange` graphQL query and you don't provide a time and the day is the same for both `fromDate` and `toDate` the default time value for `toDate` was `00:00:00`, this causes the query returns nothing because the time range is 0 seconds.
I fixed this setting `23:59:59` as default time value when the user doesn't provide a time for `toDate` variable, this way we make sure that the range will be until the last second of the day.
Use the next graphQL query and variables and comparing the results in both workspaces:
[Workspace with this fix](https://arturoreviews--sandboxusdev.myvtex.com/admin/graphql-ide)
[Workspace without this fix](https://sandboxusdev.myvtex.com/admin/graphql-ide)
```
query ReviewByDateRange(
$fromDate: String!
$toDate: String!
$orderBy: String
) { …
```
> [REVIEWS-89] reviewByDateTime and reviewByDateRange

- CHANGELOG.md
- react/ReviewForm.tsx
- react/Reviews.tsx
##Use refetch from useQuery to update the reviews list at the front
When someone save a new review at the front and the app settings has turned on `Allow Anonymous Reviews` and turned off `Require Admin Approval` the review was saved only at the back, but it was not visible in the front until refresh the page.
1.- Make sure you have on the settings turned on `Allow Anonymous Reviews` and turned off `Require Admin Approval` and turned on `Display graph`
2.- Go to any product and add a review.
3.- After submit the review you should see your review and the average updated as well as the reviews graph on product page.
The workspace below has already all necessary settings to test this fix.
[Workspace to test](https://arturoreviews--sandboxusdev.myvtex.com/)
> [REVIEWS-90] [REVIEWS-91] [REVIEWS-92] Use refetch from useQuery to update the reviews list at the front

- CHANGELOG.md
- dotnet/Controllers/RoutesController.cs
- react/admin/ApprovedReviewsTable.tsx
- react/admin/PendingReviewsTable.tsx
- react/admin/utils/dates.tsx
The admin tables pending reviews and approved was showing the time in UTC format, causing a little nonconformity for the clients who wants to see the time in their local time.
You can create a new review in this workspace and see the time of your new review at the admin
[Workspace to test](https://arturoreviews--sandboxusdev.myvtex.com/admin/reviews-ratings/approved/)
> [REVIEWS-99] Show local time in the front for admin tables

- CHANGELOG.md
- dotnet/Models/VtexOrder.cs
- graphql/schema.graphql
- react/RatingInline.tsx
- react/RatingSummary.tsx
- react/ReviewForm.tsx
- react/Reviews.tsx
- react/admin/components/DownloadTable.tsx
- react/admin/components/ReviewsTable.tsx
The previous GraphQL cache configuration was resulting in poor UX in the reviews admin. For example, if the user approved a review, it might not appear in the Approved Reviews tab immediately, and could actually continue to appear under the Pending tab, leading to confusion. 
This PR adds an appropriate amount of caching to each GraphQL query, and adjusts the admin queries to use a "network-only" fetch policy.
Linked here: https://arthur--sandboxusdev.myvtex.com/admin/reviews-ratings/pending/
Approving one of the pending reviews should now cause it to immediately appear in the Approved tab.
> Improve GraphQL caching

- CHANGELOG.md
- dotnet/Controllers/RoutesController.cs
- dotnet/DataSources/ProductReviewRepository.cs
- dotnet/GraphQL/Query.cs
- dotnet/Services/ProductReviewService.cs
- graphql/averageRatingByProductId.graphql
- graphql/deleteReview.graphql
- graphql/editReview.graphql
- graphql/hasShopperReviewed.graphql
- graphql/moderateReview.graphql
- graphql/newReview.graphql
- graphql/review.graphql
- graphql/reviewByDateRange.graphql
- graphql/reviewByreviewDateTime.graphql
- graphql/reviews.graphql
- graphql/reviewsByProductId.graphql
- graphql/reviewsByShopperId.graphql
- graphql/totalReviewsByProductId.graphql
App is unable to create MasterData schema in some cases, and this error has poor visibility.
This PR improves several things:
- calls `VerifySchema()` more often
- uses the app's auth token to authenticate the `VerifySchema()` API requests (and any other requests to VBASE or MD)
- logs an error if the app doesn't get a successful response when performing an MD search
- adds the `@context(provider: '...')` directive to all queries and mutations
Linked here: https://vta--vta.myvtex.com/admin/reviews-ratings/pending/
Previously, no reviews were showing up in the admin because the MD schema had not been applied.
> [REVIEWS-120] GraphQL and VerifySchema improvements

- cypress/support/commands.js
There is an issue in verifying the average ratings in 2.1.3 test case. We have added intercept for averageRatingsByProductId query. It should work fine now. 
**[Cypress dashboard error link](https://dashboard.cypress.io/projects/964exx/runs/195/overview)** 
**App version**: 3.11.1
[workspace](https://reviewsandratings3923653--productusqa.myvtex.com/)
> adding intecept for average rating fix

- CHANGELOG.md
- react/ReviewForm.tsx
- react/typings/global.d.ts
- react/utils/gtmPush.ts
This PR adds a custom GTM event to enable tracking of review submissions, following [these instructions](https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-sending-custom-events-to-google-tag-manager).
This PR can be used as an example for adding additional events as needed.
Linked here: https://arthur--sandboxusdev.myvtex.com/
After submitting a review, run `window.dataLayer` in the browser console and the custom event should be shown in the array.
> [REVIEWS-122] Add GTM event for submitted reviews

- CHANGELOG.md
- dotnet/Services/ProductReviewService.cs
- react/Reviews.tsx
What problem is this solving?
the previous fix about loading star causing infinite request, this PR fix both the infinite request and the PDP loading star problem. Also improved GetAverageRatingByProductId query.
How to test it?
Use Incognito mode to open link
https://esika.tiendabelcorp.cl/vibranza-perfume-de-mujer-45-ml/p?workspace=aurora111
you should see all the stars showing
open any review page to see the requests
> [REVIEWS-134] fix review state

- CHANGELOG.md
- manifest.json
- react/ReviewForm.tsx
- react/package.json
- react/queries/orders.graphql
- react/yarn.lock
The `store-graphql` orders query uses a deprecated API, and we need to remove all usage of it to shut down the endpoint. We found out that the reviews-and-ratings use this query to fetch the user orders in the `ReviewForm` component.
The goal of this fetch was to set the `verifiedPurchaser` state on the form, but this attribute is not used anymore. So we simply removed the call to the API and all related code to this attribute.
Log in and add a review to any item. The process should work with no problem
[Workspace](https://storetheme.vtex.com/?workspace=danzan)
> Removes store-graphql dependency

- CHANGELOG.md
- manifest.json
- react/ReviewForm.tsx
- react/package.json
- react/queries/orders.graphql
- react/yarn.lock
This PR removes the `store-graphql` dependency as done at #236 for the latest major version.
> Removes store-graphql dependency for major 2.x

- CHANGELOG.md
- dotnet/Services/ProductReviewService.cs
This app currently represents ~78% of wildcard queries at Master Data and it uses inffix `*{value}*` queries unnecessarily. Suffix wildcards are less expensive to calculate.
> Remove infix wildcard
